import React, { useState } from "react";
import "./DroneMissionPlanner.css";
import {
  IconActivity,
  IconShield,
  IconSparkles,
  IconCheck,
  IconRefresh,
  IconDocument,
} from "./Icons";
import { useTranslation } from "../context/LanguageContext";

const DRONE_MODELS = [
  { id: "dji-t40", name: "DJI Agras T40", tankCapacity: 40, maxSwath: 11, speed: 7.0, batteryCap: 30000 },
  { id: "dji-t30", name: "DJI Agras T30", tankCapacity: 30, maxSwath: 9, speed: 6.5, batteryCap: 29000 },
  { id: "ardupilot", name: "ArduPilot Hexacopter VTOL", tankCapacity: 16, maxSwath: 5, speed: 5.0, batteryCap: 16000 },
  { id: "xag-p100", name: "XAG P100 Pro", tankCapacity: 50, maxSwath: 10, speed: 8.0, batteryCap: 35000 },
];

const DroneMissionPlanner = ({ selectedSector = "Sector 2A (Blight Outbreak)" }) => {
  const { t } = useTranslation();
  const [selectedDrone, setSelectedDrone] = useState("dji-t40");
  const [fieldArea, setFieldArea] = useState(18.0); // Acres
  const [flightAltitude, setFlightAltitude] = useState(2.8); // meters AGL
  const [swathWidth, setSwathWidth] = useState(6.0); // meters
  const [applicationRate, setApplicationRate] = useState(15.0); // Liters / Acre
  const [chemicalName, setChemicalName] = useState("Mancozeb 75% WP (Target Blight Defense)");
  const [copiedKml, setCopiedKml] = useState(false);

  const currentDrone = DRONE_MODELS.find((d) => d.id === selectedDrone) || DRONE_MODELS[0];

  // Mathematical Flight Planning calculations
  const totalSprayVolumeNeeded = Math.round(fieldArea * applicationRate); // Liters
  const tankRefillsNeeded = Math.ceil(totalSprayVolumeNeeded / currentDrone.tankCapacity);

  // Field distance in meters (approx 1 acre = 4046.86 m²)
  const fieldAreaM2 = fieldArea * 4046.86;
  const totalLinearDistanceMeters = Math.round(fieldAreaM2 / swathWidth);
  const totalFlightTimeSeconds = Math.round(totalLinearDistanceMeters / currentDrone.speed);
  const totalFlightTimeMinutes = (totalFlightTimeSeconds / 60).toFixed(1);

  const estimatedBatteryCycles = Math.ceil(totalFlightTimeSeconds / 720); // ~12 min per battery

  // Generate authentic LaTeX (.tex) source file
  const generateLatexSource = () => {
    const lat = 40.7128;
    const lon = -74.006;
    const dateStr = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    return `% ==============================================================================
% AGROPATH AUTONOMOUS FLIGHT SYSTEMS: UAV SPRAY MISSION DOSSIER
% Generated by AgroPath AI Precision Agriculture Engine
% ==============================================================================
\\documentclass[10pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[margin=0.75in]{geometry}
\\usepackage{amsmath,amssymb}
\\usepackage{booktabs}
\\usepackage{tabularx}
\\usepackage{xcolor}
\\usepackage{fancyhdr}
\\usepackage{tcolorbox}
\\usepackage{titlesec}
\\usepackage{hyperref}

\\definecolor{agroPrimary}{RGB}{14, 116, 144}
\\definecolor{agroGreen}{RGB}{22, 101, 52}
\\definecolor{agroDark}{RGB}{15, 23, 42}
\\definecolor{agroLight}{RGB}{248, 250, 252}

\\pagestyle{fancy}
\\fancyhf{}
\\lhead{\\textbf{\\textcolor{agroPrimary}{AgroPath AI}} \\textbar\\ Flight Operations Directorate}
\\rhead{\\textsf{Sector: ${selectedSector}}}
\\cfoot{\\thepage}
\\renewcommand{\\headrulewidth}{0.6pt}

\\begin{document}

\\begin{center}
    {\\Large \\textbf{\\textsc{Precision UAV Foliar Application Mission Dossier}}}\\\\[2pt]
    {\\small \\textbf{Autonomous Aviation Flight Clearance \\& Waypoint Trajectory Protocol}}\\\\[4pt]
    {\\footnotesize \\textit{Issued: ${dateStr} \\textbullet\\ Flight Authority ID: \\texttt{AGR-FLT-${Date.now().toString().slice(-6)}}}}
\\end{center}

\\vspace{-4pt}
\\noindent\\rule{\\textwidth}{1.2pt}
\\vspace{6pt}

\\section*{\\normalsize 1. Mission Overview \\& UAV Platform Specifications}
\\noindent
\\begin{tabularx}{\\textwidth}{|l X|l X|}
\\hline
\\textbf{Airframe Model:} & ${currentDrone.name} & \\textbf{Target Sector:} & ${selectedSector} \\\\
\\textbf{Effective Swath ($w$):} & ${swathWidth}\\text{ m} & \\textbf{Flight Altitude ($h_{AGL}$):} & ${flightAltitude}\\text{ m AGL} \\\\
\\textbf{Ground Speed ($v$):} & ${currentDrone.speed}\\text{ m/s} (${(currentDrone.speed * 3.6).toFixed(1)}\\text{ km/h}) & \\textbf{Application Rate ($R$):} & ${applicationRate}\\text{ L/Acre} \\\\
\\textbf{Total Target Area ($A$):} & ${fieldArea}\\text{ Acres} (${(fieldArea * 0.404686).toFixed(2)}\\text{ Hectares}) & \\textbf{Tank Payload:} & ${currentDrone.tankCapacity}\\text{ L per sort} \\\\
\\hline
\\end{tabularx}

\\section*{\\normalsize 2. Mathematical Telemetry \\& Aerodynamic Spray Dynamics}
\\noindent
The linear flight path distance ($L$) and continuous application flow rate ($Q$) are derived via:
\\begin{equation}
L = \\frac{A_{\\text{m}^2}}{w} = \\frac{${fieldArea} \\times 4046.86}{${swathWidth}} = ${totalLinearDistanceMeters.toLocaleString()}\\text{ meters} \\quad (${(totalLinearDistanceMeters / 1000).toFixed(2)}\\text{ km})
\\end{equation}
\\begin{equation}
Q = \\frac{R_{\\text{L/ha}} \\times w_{\\text{m}} \\times v_{\\text{m/s}}}{600} = \\frac{${(applicationRate * 2.471).toFixed(1)} \\times ${swathWidth} \\times ${currentDrone.speed}}{600} = ${( (applicationRate * 2.471 * swathWidth * currentDrone.speed) / 600 ).toFixed(2)}\\text{ L/min}
\\end{equation}

\\begin{tcolorbox}[colback=agroLight,colframe=agroPrimary,title=\\textbf{Operational Sortie Summary}]
\\begin{itemize}\\setlength\\itemsep{1pt}
    \\item \\textbf{Total Solution Volume Needed:} ${totalSprayVolumeNeeded}\\text{ Liters} (Requires \\textbf{${tankRefillsNeeded} Tank Sorties})
    \\item \\textbf{Active Flight Duration:} ${totalFlightTimeMinutes}\\text{ Minutes} (\\textbf{${estimatedBatteryCycles} Smart LiPo Battery Cycles} @ ${currentDrone.batteryCap}\\text{ mAh})
    \\item \\textbf{Prescribed Agrochemical:} \\texttt{${chemicalName}}
\\end{itemize}
\\end{tcolorbox}

\\section*{\\normalsize 3. Autonomous Waypoint Trajectory Grid (WGS-84)}
\\noindent
\\begin{tabularx}{\\textwidth}{c c c c c X}
\\toprule
\\textbf{Index} & \\textbf{Latitude ($^\\circ$N)} & \\textbf{Longitude ($^\\circ$E)} & \\textbf{Alt (m)} & \\textbf{Speed (m/s)} & \\textbf{Action / Command} \\\\
\\midrule
WP 0 & ${lat.toFixed(4)} & ${(lon).toFixed(4)} & 0.0 & 0.0 & Home / VTOL Armed Takeoff \\\\
WP 1 & ${(lat + 0.0005).toFixed(4)} & ${(lon + 0.0005).toFixed(4)} & ${flightAltitude} & ${currentDrone.speed} & Engage Spray Valve (Swath 1 Entry) \\\\
WP 2 & ${(lat + 0.0025).toFixed(4)} & ${(lon + 0.0005).toFixed(4)} & ${flightAltitude} & ${currentDrone.speed} & Linear Foliar Application \\\\
WP 3 & ${(lat + 0.0025).toFixed(4)} & ${(lon + 0.0015).toFixed(4)} & ${flightAltitude} & 3.0 & Bank Turn \\& Swath Shift (${swathWidth}m) \\\\
WP 4 & ${(lat + 0.0005).toFixed(4)} & ${(lon + 0.0015).toFixed(4)} & ${flightAltitude} & ${currentDrone.speed} & Return Spray Pass (Swath 2) \\\\
WP 5 & ${lat.toFixed(4)} & ${(lon).toFixed(4)} & 0.0 & 2.0 & RTL (Return-to-Launch) \\& Auto-Land \\\\
\\bottomrule
\\end{tabularx}

\\section*{\\normalsize 4. Flight Safety, Drift Mitigation \\& Legal Clearance Sign-Off}
\\noindent
\\textit{Certified that the flight plan complies with FAA Part 107 / CAA Agricultural UAV Operations directives. Wind threshold: $\\le 4.5\\text{ m/s}$; Drift buffer zone: $15\\text{ m}$.}

\\vspace{14pt}
\\noindent
\\begin{tabularx}{\\textwidth}{X X}
\\textbf{Remote Pilot in Command (RPIC):} & \\textbf{Lead Consulting Agronomist:} \\\\[18pt]
\\rule{0.8\\linewidth}{0.6pt} & \\rule{0.8\\linewidth}{0.6pt} \\\\
\\footnotesize Signature \\& License No. & \\footnotesize Signature \\& Accreditation No.
\\end{tabularx}

\\end{document}`;
  };

  // Download raw LaTeX .tex file
  const handleDownloadTex = () => {
    const texData = generateLatexSource();
    const blob = new Blob([texData], { type: "text/x-tex;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AgroPath_FlightDossier_${Date.now()}.tex`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Render & Open Print/Save-as-PDF Window with pristine LaTeX styling
  const handleExportPdf = () => {
    const lat = 40.7128;
    const lon = -74.006;
    const dateStr = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const flowRate = ((applicationRate * 2.471 * swathWidth * currentDrone.speed) / 600).toFixed(2);
    const flightId = `AGR-FLT-${Date.now().toString().slice(-6)}`;

    const printHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Flight Mission Dossier - ${flightId}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@700&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@500;700&display=swap" rel="stylesheet">
  <style>
    @page {
      size: A4;
      margin: 20mm 18mm 20mm 18mm;
    }
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      font-family: 'Lora', 'Latin Modern Roman', 'Times New Roman', serif;
      color: #111827;
      background: #ffffff;
      line-height: 1.5;
      font-size: 11pt;
      padding: 24px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header-bar {
      display: flex;
      justify-content: space-between;
      border-bottom: 1.5px solid #0e7490;
      padding-bottom: 6px;
      margin-bottom: 18px;
      font-size: 8.5pt;
      color: #4b5563;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .header-bar strong {
      color: #0e7490;
      font-weight: 700;
    }
    .doc-title {
      text-align: center;
      margin-bottom: 16px;
    }
    .doc-title h1 {
      font-family: 'Cinzel', serif;
      font-size: 18pt;
      font-weight: 700;
      color: #0f172a;
      letter-spacing: 0.04em;
    }
    .doc-title h2 {
      font-size: 11pt;
      font-weight: 600;
      color: #334155;
      margin-top: 2px;
    }
    .doc-title .meta-line {
      font-size: 8.5pt;
      color: #64748b;
      margin-top: 4px;
      font-style: italic;
    }
    .double-rule {
      border-top: 1.5px solid #0f172a;
      border-bottom: 0.5px solid #0f172a;
      height: 3px;
      margin: 12px 0 18px 0;
    }
    .sec-title {
      font-size: 11.5pt;
      font-weight: 700;
      color: #0f172a;
      border-bottom: 1px solid #cbd5e1;
      padding-bottom: 3px;
      margin: 18px 0 10px 0;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }
    table.data-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 9.5pt;
      margin-bottom: 14px;
    }
    table.data-table th, table.data-table td {
      border: 1px solid #cbd5e1;
      padding: 6px 10px;
      text-align: left;
    }
    table.data-table th {
      background: #f8fafc;
      font-weight: 700;
      color: #1e293b;
    }
    .math-block {
      background: #f8fafc;
      border-left: 3px solid #0e7490;
      padding: 10px 14px;
      margin: 12px 0;
      font-family: 'Lora', serif;
      font-size: 10pt;
      font-style: italic;
    }
    .math-block .eq {
      font-family: 'JetBrains Mono', monospace;
      font-style: normal;
      font-weight: 600;
      color: #0e7490;
      display: block;
      margin: 4px 0;
    }
    .box-container {
      border: 1.5px solid #0e7490;
      background: #f0fdfa;
      border-radius: 6px;
      padding: 12px 16px;
      margin: 14px 0;
    }
    .box-container h3 {
      color: #0e7490;
      font-size: 10.5pt;
      font-weight: 700;
      margin-bottom: 6px;
    }
    .box-container ul {
      margin-left: 20px;
      font-size: 9.5pt;
    }
    .box-container li {
      margin-bottom: 3px;
    }
    table.waypoint-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 9pt;
      margin: 10px 0;
    }
    table.waypoint-table th {
      border-top: 1.5px solid #0f172a;
      border-bottom: 1.5px solid #0f172a;
      padding: 6px 8px;
      text-align: left;
      font-weight: 700;
    }
    table.waypoint-table td {
      border-bottom: 0.5px solid #e2e8f0;
      padding: 6px 8px;
    }
    table.waypoint-table tr:last-child td {
      border-bottom: 1.5px solid #0f172a;
    }
    .signature-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 30px;
      margin-top: 30px;
      padding-top: 10px;
    }
    .sig-col {
      display: flex;
      flex-direction: column;
    }
    .sig-line {
      border-bottom: 1px solid #475569;
      height: 40px;
      margin-bottom: 6px;
    }
    .sig-label {
      font-size: 8.5pt;
      color: #64748b;
    }
    .stamp-box {
      border: 2px dashed #16a34a;
      color: #16a34a;
      font-weight: 700;
      text-transform: uppercase;
      padding: 6px 12px;
      display: inline-block;
      border-radius: 4px;
      font-size: 8.5pt;
      margin-top: 10px;
    }
    .print-actions {
      position: fixed;
      bottom: 20px;
      right: 20px;
      display: flex;
      gap: 10px;
      z-index: 1000;
    }
    .print-btn {
      background: #0e7490;
      color: #fff;
      border: none;
      padding: 10px 18px;
      border-radius: 8px;
      font-weight: 700;
      cursor: pointer;
      font-family: sans-serif;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }
    .print-btn:hover { background: #0891b2; }
    @media print {
      .print-actions { display: none; }
      body { padding: 0; max-width: 100%; }
    }
  </style>
</head>
<body>
  <div class="print-actions">
    <button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
  </div>

  <div class="header-bar">
    <div><strong>AgroPath AI</strong> | Flight Operations Directorate</div>
    <div>Sector: ${selectedSector}</div>
  </div>

  <div class="doc-title">
    <h1>PRECISION UAV FOLIAR APPLICATION MISSION DOSSIER</h1>
    <h2>Autonomous Aviation Flight Clearance &amp; Waypoint Trajectory Protocol</h2>
    <div class="meta-line">Issued: ${dateStr} &bull; Authority Reference: ${flightId}</div>
  </div>

  <div class="double-rule"></div>

  <div class="sec-title">1. Mission Overview &amp; UAV Platform Specifications</div>
  <table class="data-table">
    <tr>
      <td><strong>Airframe Model:</strong> ${currentDrone.name}</td>
      <td><strong>Target Sector:</strong> ${selectedSector}</td>
    </tr>
    <tr>
      <td><strong>Effective Swath (w):</strong> ${swathWidth} meters</td>
      <td><strong>Flight Altitude (h AGL):</strong> ${flightAltitude} meters AGL</td>
    </tr>
    <tr>
      <td><strong>Cruise Speed (v):</strong> ${currentDrone.speed} m/s (${(currentDrone.speed * 3.6).toFixed(1)} km/h)</td>
      <td><strong>Application Rate (R):</strong> ${applicationRate} L / Acre</td>
    </tr>
    <tr>
      <td><strong>Total Target Area (A):</strong> ${fieldArea} Acres (${(fieldArea * 0.404686).toFixed(2)} Ha)</td>
      <td><strong>Tank Capacity:</strong> ${currentDrone.tankCapacity} Liters</td>
    </tr>
  </table>

  <div class="sec-title">2. Mathematical Telemetry &amp; Aerodynamic Spray Dynamics</div>
  <div class="math-block">
    Linear Flight Line Distance:
    <div class="eq">L = A_m2 / w = (${fieldArea} &times; 4046.86) / ${swathWidth} = ${totalLinearDistanceMeters.toLocaleString()} m (${(totalLinearDistanceMeters / 1000).toFixed(2)} km)</div>
    Continuous Application Flow Rate:
    <div class="eq">Q = (R_L/ha &times; w_m &times; v_m/s) / 600 = (${(applicationRate * 2.471).toFixed(1)} &times; ${swathWidth} &times; ${currentDrone.speed}) / 600 = ${flowRate} L/min</div>
  </div>

  <div class="box-container">
    <h3>Operational Sortie Summary</h3>
    <ul>
      <li><strong>Total Chemical Spray Solution:</strong> ${totalSprayVolumeNeeded} Liters (&rArr; Requires <strong>${tankRefillsNeeded} Tank Sorties</strong> of ${currentDrone.tankCapacity}L)</li>
      <li><strong>Active Total Mission Time:</strong> ${totalFlightTimeMinutes} Minutes (&rArr; <strong>${estimatedBatteryCycles} Smart LiPo Battery Packs</strong> @ ${currentDrone.batteryCap} mAh)</li>
      <li><strong>Target Formulation:</strong> ${chemicalName}</li>
    </ul>
  </div>

  <div class="sec-title">3. Autonomous Waypoint Trajectory Grid (WGS-84 Telemetry)</div>
  <table class="waypoint-table">
    <thead>
      <tr>
        <th>WP Index</th>
        <th>Latitude (&deg;N)</th>
        <th>Longitude (&deg;E)</th>
        <th>Altitude</th>
        <th>Speed</th>
        <th>Action / Mission Event</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>WP 0</strong></td>
        <td>${lat.toFixed(4)}</td>
        <td>${lon.toFixed(4)}</td>
        <td>0.0 m</td>
        <td>0.0 m/s</td>
        <td>Home / Armed Takeoff &amp; Sensor Calibration</td>
      </tr>
      <tr>
        <td><strong>WP 1</strong></td>
        <td>${(lat + 0.0005).toFixed(4)}</td>
        <td>${(lon + 0.0005).toFixed(4)}</td>
        <td>${flightAltitude} m</td>
        <td>${currentDrone.speed} m/s</td>
        <td>Engage Foliar Spray Nozzles (Swath 1 Entry)</td>
      </tr>
      <tr>
        <td><strong>WP 2</strong></td>
        <td>${(lat + 0.0025).toFixed(4)}</td>
        <td>${(lon + 0.0005).toFixed(4)}</td>
        <td>${flightAltitude} m</td>
        <td>${currentDrone.speed} m/s</td>
        <td>Precision Application Line</td>
      </tr>
      <tr>
        <td><strong>WP 3</strong></td>
        <td>${(lat + 0.0025).toFixed(4)}</td>
        <td>${(lon + 0.0015).toFixed(4)}</td>
        <td>${flightAltitude} m</td>
        <td>3.0 m/s</td>
        <td>Autonomous Bank Turn &amp; Swath Shift (${swathWidth}m)</td>
      </tr>
      <tr>
        <td><strong>WP 4</strong></td>
        <td>${(lat + 0.0005).toFixed(4)}</td>
        <td>${(lon + 0.0015).toFixed(4)}</td>
        <td>${flightAltitude} m</td>
        <td>${currentDrone.speed} m/s</td>
        <td>Return Spray Pass (Swath 2 Coverage)</td>
      </tr>
      <tr>
        <td><strong>WP 5</strong></td>
        <td>${lat.toFixed(4)}</td>
        <td>${lon.toFixed(4)}</td>
        <td>0.0 m</td>
        <td>2.0 m/s</td>
        <td>RTL (Return to Launch) &amp; Soft Touchdown</td>
      </tr>
    </tbody>
  </table>

  <div class="sec-title">4. Flight Safety, Drift Mitigation &amp; Clearance Sign-off</div>
  <p style="font-size: 9.5pt; color: #334155; margin-bottom: 8px;">
    <em>This autonomous trajectory complies with FAA Part 107 / CAA Agricultural Aviation Directives. Operation is certified for ground wind speeds &le; 4.5 m/s with a 15-meter active drift buffer.</em>
  </p>
  <div class="stamp-box">&check; AERODYNAMIC FLIGHT CLEARANCE GRANTED</div>

  <div class="signature-grid">
    <div class="sig-col">
      <div class="sig-line"></div>
      <div class="sig-label"><strong>Remote Pilot in Command (RPIC)</strong><br>Commercial UAV License &amp; Sign-off</div>
    </div>
    <div class="sig-col">
      <div class="sig-line"></div>
      <div class="sig-label"><strong>Lead Agronomist / Bio-Security Inspector</strong><br>Crop Health Certification Officer</div>
    </div>
  </div>
</body>
</html>`;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.open();
      printWindow.document.write(printHtml);
      printWindow.document.close();
      // Allow fonts to load before triggering print dialog
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  };

  return (
    <div className="drone-planner-card">
      <div className="planner-header-row">
        <div className="planner-title-col">
          <div className="planner-badge">
            <span className="planner-dot"></span>
            <span>Autonomous Agricultural Aviation Planner</span>
          </div>
          <h3 className="planner-main-heading">
            Precision Drone Spray Mission & Waypoint Generator
          </h3>
          <p className="planner-sub-desc">
            Calculate flight telemetry, chemical payload volume, swath overlap, and export publication-grade LaTeX flight dossiers and PDF clearance certificates.
          </p>
        </div>
      </div>

      {/* Inputs Configuration Grid */}
      <div className="planner-inputs-grid">
        <div className="planner-field">
          <label>UAV Airframe Model</label>
          <select
            value={selectedDrone}
            onChange={(e) => setSelectedDrone(e.target.value)}
          >
            {DRONE_MODELS.map((d) => (
              <option key={d.id} value={d.id}>
                {d.name} ({d.tankCapacity}L Tank • {d.maxSwath}m Swath)
              </option>
            ))}
          </select>
        </div>

        <div className="planner-field">
          <label>Target Area (Acres)</label>
          <input
            type="number"
            min="0.5"
            max="1000"
            step="0.5"
            value={fieldArea}
            onChange={(e) => setFieldArea(Math.max(0.5, Number(e.target.value)))}
          />
        </div>

        <div className="planner-field">
          <label>Flight Altitude AGL (Meters)</label>
          <input
            type="number"
            min="1.5"
            max="10.0"
            step="0.1"
            value={flightAltitude}
            onChange={(e) => setFlightAltitude(Number(e.target.value))}
          />
        </div>

        <div className="planner-field">
          <label>Spray Swath Width (Meters)</label>
          <input
            type="number"
            min="2.0"
            max="15.0"
            step="0.5"
            value={swathWidth}
            onChange={(e) => setSwathWidth(Number(e.target.value))}
          />
        </div>

        <div className="planner-field">
          <label>Liquid Application Rate (L / Acre)</label>
          <input
            type="number"
            min="5"
            max="50"
            value={applicationRate}
            onChange={(e) => setApplicationRate(Number(e.target.value))}
          />
        </div>

        <div className="planner-field full-width">
          <label>Prescribed Chemical Formulation</label>
          <input
            type="text"
            value={chemicalName}
            onChange={(e) => setChemicalName(e.target.value)}
          />
        </div>
      </div>

      {/* Flight Telemetry Dashboard Metrics */}
      <div className="drone-telemetry-metrics">
        <div className="metric-box">
          <span className="m-label">Total Spray Volume</span>
          <span className="m-val">{totalSprayVolumeNeeded} Liters</span>
          <span className="m-sub">{tankRefillsNeeded} Tank Loads ({currentDrone.tankCapacity}L each)</span>
        </div>

        <div className="metric-box">
          <span className="m-label">Flight Distance</span>
          <span className="m-val">{(totalLinearDistanceMeters / 1000).toFixed(2)} km</span>
          <span className="m-sub">{totalLinearDistanceMeters.toLocaleString()} m Total Line</span>
        </div>

        <div className="metric-box">
          <span className="m-label">Estimated Flight Time</span>
          <span className="m-val highlight">{totalFlightTimeMinutes} Mins</span>
          <span className="m-sub">Speed: {currentDrone.speed} m/s</span>
        </div>

        <div className="metric-box">
          <span className="m-label">Battery Cycles</span>
          <span className="m-val">{estimatedBatteryCycles} Smart Packs</span>
          <span className="m-sub">Capacity: {currentDrone.batteryCap} mAh</span>
        </div>
      </div>

      {/* Interactive LaTeX PDF Export Bar */}
      <div className="drone-export-actions-bar">
        <div className="export-text">
          <span className="export-title">Export Flight Mission Dossier (LaTeX Format):</span>
          <span className="export-sub">High-precision mathematical flight report with aerodynamic equations, waypoint trajectory grid, and FAA clearance certificate.</span>
        </div>

        <div className="export-buttons-row">
          <button type="button" className="latex-pdf-btn" onClick={handleExportPdf}>
            <IconDocument size={16} />
            <span>Export Mission Dossier (LaTeX PDF)</span>
          </button>

          <button type="button" className="latex-tex-btn" onClick={handleDownloadTex}>
            <IconActivity size={16} />
            <span>Download LaTeX Source (.TEX)</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default DroneMissionPlanner;
