import React, { useState } from "react";
import "./DroneMissionPlanner.css";
import {
  IconActivity,
  IconShield,
  IconSparkles,
  IconCheck,
  IconRefresh,
  IconDocument,
} from "./Icons";
import { useTranslation } from "../context/LanguageContext";

const DRONE_MODELS = [
  { id: "dji-t40", name: "DJI Agras T40", tankCapacity: 40, maxSwath: 11, speed: 7.0, batteryCap: 30000 },
  { id: "dji-t30", name: "DJI Agras T30", tankCapacity: 30, maxSwath: 9, speed: 6.5, batteryCap: 29000 },
  { id: "ardupilot", name: "ArduPilot Hexacopter VTOL", tankCapacity: 16, maxSwath: 5, speed: 5.0, batteryCap: 16000 },
  { id: "xag-p100", name: "XAG P100 Pro", tankCapacity: 50, maxSwath: 10, speed: 8.0, batteryCap: 35000 },
];

const DroneMissionPlanner = ({ selectedSector = "Sector 2A (Blight Outbreak)" }) => {
  const { t } = useTranslation();
  const [selectedDrone, setSelectedDrone] = useState("dji-t40");
  const [fieldArea, setFieldArea] = useState(18.0); // Acres
  const [flightAltitude, setFlightAltitude] = useState(2.8); // meters AGL
  const [swathWidth, setSwathWidth] = useState(6.0); // meters
  const [applicationRate, setApplicationRate] = useState(15.0); // Liters / Acre
  const [chemicalName, setChemicalName] = useState("Mancozeb 75% WP (Target Blight Defense)");
  const [copiedKml, setCopiedKml] = useState(false);

  const currentDrone = DRONE_MODELS.find((d) => d.id === selectedDrone) || DRONE_MODELS[0];

  // Mathematical Flight Planning calculations
  const totalSprayVolumeNeeded = Math.round(fieldArea * applicationRate); // Liters
  const tankRefillsNeeded = Math.ceil(totalSprayVolumeNeeded / currentDrone.tankCapacity);

  // Field distance in meters (approx 1 acre = 4046.86 m²)
  const fieldAreaM2 = fieldArea * 4046.86;
  const totalLinearDistanceMeters = Math.round(fieldAreaM2 / swathWidth);
  const totalFlightTimeSeconds = Math.round(totalLinearDistanceMeters / currentDrone.speed);
  const totalFlightTimeMinutes = (totalFlightTimeSeconds / 60).toFixed(1);

  const estimatedBatteryCycles = Math.ceil(totalFlightTimeSeconds / 720); // ~12 min per battery

  // Generate standard KML XML flight file for DJI Agras / ArduPilot
  const generateKmlContent = () => {
    const lat = 40.7128;
    const lon = -74.006;
    return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>AgroPath_DroneMission_${selectedSector.replace(/\s+/g, "_")}</name>
    <description>Autonomous precision foliar fungicide flight path generated by AgroPath AI.</description>
    <Placemark>
      <name>Takeoff & Spray Boundary</name>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>
              ${lon},${lat},${flightAltitude}
              ${lon + 0.003},${lat},${flightAltitude}
              ${lon + 0.003},${lat + 0.003},${flightAltitude}
              ${lon},${lat + 0.003},${flightAltitude}
              ${lon},${lat},${flightAltitude}
            </coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>
    <Placemark>
      <name>Waypoint Grid - ${chemicalName}</name>
      <LineString>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>
          ${lon + 0.0005},${lat + 0.0005},${flightAltitude}
          ${lon + 0.0025},${lat + 0.0005},${flightAltitude}
          ${lon + 0.0025},${lat + 0.0015},${flightAltitude}
          ${lon + 0.0005},${lat + 0.0015},${flightAltitude}
          ${lon + 0.0005},${lat + 0.0025},${flightAltitude}
          ${lon + 0.0025},${lat + 0.0025},${flightAltitude}
        </coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>`;
  };

  const handleDownloadKml = () => {
    const kmlData = generateKmlContent();
    const blob = new Blob([kmlData], { type: "application/vnd.google-earth.kml+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AgroPath_Mission_${Date.now()}.kml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadMission = () => {
    const missionText = `QGC WPL 110
0\t1\t0\t16\t0\t0\t0\t0\t40.7128\t-74.006\t${flightAltitude}\t1
1\t0\t3\t16\t0\t0\t0\t0\t40.7132\t-74.0055\t${flightAltitude}\t1
2\t0\t3\t16\t0\t0\t0\t0\t40.7145\t-74.0055\t${flightAltitude}\t1
3\t0\t3\t16\t0\t0\t0\t0\t40.7145\t-74.0045\t${flightAltitude}\t1
4\t0\t3\t16\t0\t0\t0\t0\t40.7132\t-74.0045\t${flightAltitude}\t1
5\t0\t3\t20\t0\t0\t0\t0\t40.7128\t-74.006\t0\t1`;

    const blob = new Blob([missionText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AgroPath_ArduPilot_${Date.now()}.waypoints`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="drone-planner-card">
      <div className="planner-header-row">
        <div className="planner-title-col">
          <div className="planner-badge">
            <span className="planner-dot"></span>
            <span>Autonomous Agricultural Aviation Planner</span>
          </div>
          <h3 className="planner-main-heading">
            Precision Drone Spray Mission & Waypoint Generator
          </h3>
          <p className="planner-sub-desc">
            Calculate flight telemetry, chemical payload volume, swath overlap, and export ready-to-fly DJI / ArduPilot autonomous flight files.
          </p>
        </div>
      </div>

      {/* Inputs Configuration Grid */}
      <div className="planner-inputs-grid">
        <div className="planner-field">
          <label>UAV Airframe Model</label>
          <select
            value={selectedDrone}
            onChange={(e) => setSelectedDrone(e.target.value)}
          >
            {DRONE_MODELS.map((d) => (
              <option key={d.id} value={d.id}>
                {d.name} ({d.tankCapacity}L Tank • {d.maxSwath}m Swath)
              </option>
            ))}
          </select>
        </div>

        <div className="planner-field">
          <label>Target Area (Acres)</label>
          <input
            type="number"
            min="0.5"
            max="1000"
            step="0.5"
            value={fieldArea}
            onChange={(e) => setFieldArea(Math.max(0.5, Number(e.target.value)))}
          />
        </div>

        <div className="planner-field">
          <label>Flight Altitude AGL (Meters)</label>
          <input
            type="number"
            min="1.5"
            max="10.0"
            step="0.1"
            value={flightAltitude}
            onChange={(e) => setFlightAltitude(Number(e.target.value))}
          />
        </div>

        <div className="planner-field">
          <label>Spray Swath Width (Meters)</label>
          <input
            type="number"
            min="2.0"
            max="15.0"
            step="0.5"
            value={swathWidth}
            onChange={(e) => setSwathWidth(Number(e.target.value))}
          />
        </div>

        <div className="planner-field">
          <label>Liquid Application Rate (L / Acre)</label>
          <input
            type="number"
            min="5"
            max="50"
            value={applicationRate}
            onChange={(e) => setApplicationRate(Number(e.target.value))}
          />
        </div>

        <div className="planner-field full-width">
          <label>Prescribed Chemical Formulation</label>
          <input
            type="text"
            value={chemicalName}
            onChange={(e) => setChemicalName(e.target.value)}
          />
        </div>
      </div>

      {/* Flight Telemetry Dashboard Metrics */}
      <div className="drone-telemetry-metrics">
        <div className="metric-box">
          <span className="m-label">Total Spray Volume</span>
          <span className="m-val">{totalSprayVolumeNeeded} Liters</span>
          <span className="m-sub">{tankRefillsNeeded} Tank Loads ({currentDrone.tankCapacity}L each)</span>
        </div>

        <div className="metric-box">
          <span className="m-label">Flight Distance</span>
          <span className="m-val">{(totalLinearDistanceMeters / 1000).toFixed(2)} km</span>
          <span className="m-sub">{totalLinearDistanceMeters.toLocaleString()} m Total Line</span>
        </div>

        <div className="metric-box">
          <span className="m-label">Estimated Flight Time</span>
          <span className="m-val highlight">{totalFlightTimeMinutes} Mins</span>
          <span className="m-sub">Speed: {currentDrone.speed} m/s</span>
        </div>

        <div className="metric-box">
          <span className="m-label">Battery Cycles</span>
          <span className="m-val">{estimatedBatteryCycles} Smart Packs</span>
          <span className="m-sub">Capacity: {currentDrone.batteryCap} mAh</span>
        </div>
      </div>

      {/* Interactive Waypoint Export Bar */}
      <div className="drone-export-actions-bar">
        <div className="export-text">
          <span className="export-title">Export Autonomous Flight Path:</span>
          <span className="export-sub">Directly compatible with DJI Smart Controller, DJI Agras, and QGroundControl.</span>
        </div>

        <div className="export-buttons-row">
          <button type="button" className="kml-btn" onClick={handleDownloadKml}>
            <IconDocument size={16} />
            <span>Download DJI .KML Flight File</span>
          </button>

          <button type="button" className="mission-btn" onClick={handleDownloadMission}>
            <IconActivity size={16} />
            <span>Download ArduPilot .WAYPOINTS</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default DroneMissionPlanner;
