import React, { useState } from "react";
import "./WorkerDispatchModal.css";
import { IconWhatsApp, IconShare, IconCopy, IconCheck, IconSend } from "./Icons";

const WorkerDispatchModal = ({ isOpen, onClose, predictionData, dosageData }) => {
  const [plotName, setPlotName] = useState("Sector 4A - North Plot");
  const [workerPhone, setWorkerPhone] = useState("");
  const [customNotes, setCustomNotes] = useState("Apply in early morning before wind speed exceeds 10 km/h.");
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const diseaseName = predictionData?.disease_name || predictionData?.class || "Late Blight";
  const confidence = predictionData?.confidence ? `${(predictionData.confidence * 100).toFixed(1)}%` : "98.4%";
  const chemical = dosageData?.chemical || "Mancozeb 75% WP";
  const dosageRate = dosageData?.recommendedDosage || "2.5 kg / hectare";
  const waterVol = dosageData?.waterVolume || "500 Liters / hectare";

  // Formatted message payload (Strictly zero emojis)
  const dispatchMessage = `[AGROPATH FIELD DIRECTIVE]
TARGET PLOT: ${plotName}
DIAGNOSIS: ${diseaseName} (Confidence: ${confidence})

ACTION REQUIRED:
1. Chemical: ${chemical}
2. Dosage: ${dosageRate}
3. Water Carrier: ${waterVol}
4. Safety PPE: Nitrile Gloves, Respirator Mask, Protective Goggles.
5. Re-Entry Interval (REI): 24 Hours quarantine.

FIELD SUPERVISOR NOTES:
${customNotes}

Generated by AgroPath AI Diagnostic Engine.`;

  const encodedMsg = encodeURIComponent(dispatchMessage);
  const whatsappUrl = workerPhone
    ? `https://api.whatsapp.com/send?phone=${workerPhone.replace(/[^0-9]/g, "")}&text=${encodedMsg}`
    : `https://api.whatsapp.com/send?text=${encodedMsg}`;

  const smsUrl = workerPhone
    ? `sms:${workerPhone}?body=${encodedMsg}`
    : `sms:?body=${encodedMsg}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(dispatchMessage);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="dispatch-modal-overlay">
      <div className="dispatch-modal-box">
        <div className="dispatch-modal-header">
          <div className="dispatch-title-group">
            <div className="dispatch-icon-frame">
              <IconShare size={18} />
            </div>
            <div>
              <h3 className="dispatch-main-title">Dispatch Field Crew Directive</h3>
              <p className="dispatch-sub-title">1-Click WhatsApp, SMS & direct dispatch for spray application teams</p>
            </div>
          </div>
          <button type="button" className="dispatch-close-btn" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="dispatch-body">
          <div className="dispatch-form-row">
            <div className="dispatch-input-col">
              <label>Target Field Plot</label>
              <input
                type="text"
                className="dispatch-input"
                value={plotName}
                onChange={(e) => setPlotName(e.target.value)}
              />
            </div>
            <div className="dispatch-input-col">
              <label>Worker WhatsApp / Phone (Optional)</label>
              <input
                type="tel"
                className="dispatch-input"
                placeholder="+1 555-0199 or +91 98765..."
                value={workerPhone}
                onChange={(e) => setWorkerPhone(e.target.value)}
              />
            </div>
          </div>

          <div className="dispatch-input-col">
            <label>Supervisor Instructions</label>
            <input
              type="text"
              className="dispatch-input"
              value={customNotes}
              onChange={(e) => setCustomNotes(e.target.value)}
            />
          </div>

          <div className="dispatch-preview-container">
            <label className="preview-label">Generated Transmission Preview</label>
            <pre className="dispatch-preview-code">{dispatchMessage}</pre>
          </div>
        </div>

        <div className="dispatch-actions-bar">
          <button
            type="button"
            className="dispatch-action-btn copy-btn"
            onClick={handleCopy}
          >
            {copied ? <IconCheck size={16} /> : <IconCopy size={16} />}
            <span>{copied ? "Copied to Clipboard" : "Copy Text"}</span>
          </button>

          <a
            href={smsUrl}
            className="dispatch-action-btn sms-btn"
          >
            <IconSend size={16} />
            <span>Send SMS</span>
          </a>

          <a
            href={whatsappUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="dispatch-action-btn whatsapp-btn"
          >
            <IconWhatsApp size={16} />
            <span>Send WhatsApp</span>
          </a>
        </div>
      </div>
    </div>
  );
};

export default WorkerDispatchModal;
