import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5001";

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
];

// Instant Zero-Latency UI Localization Dictionary
export const UI_DICTIONARY = {
  en: {
    nav_home: "Home",
    nav_scanner: "Scanner",
    nav_twin: "Digital Twin",
    nav_radar: "Radar",
    nav_dosage: "Dosage",
    nav_encyclopedia: "Encyclopedia",
    nav_journal: "Journal",
    nav_scan_leaf: "Scan Leaf",
    system_ready: "System Ready",
    api_offline: "API Offline",
    tagline: "Plant Pathology System",
    hero_title: "AI Precision Agronomy & Crop Disease Intelligence",
    hero_subtitle: "Instant neural diagnostics, microclimate spore forecasting, and autonomous drone defense for growers worldwide.",
    start_diagnosis: "Start Diagnosis",
    explore_twin: "Explore Farm Twin",
    dosage_calc: "Dosage Calculator",
    spore_radar: "Spore Radar",
    plant_encyclopedia: "Encyclopedia",
    scan_history: "Scan History",
    how_it_works: "How It Works",
    select_field: "Select a Field",
    send_drone: "Spray with Drone",
    water_fields: "Water All Fields",
    simulate_outbreak: "Simulate Outbreak",
    reset_farm: "Reset Farm",
    crop_health: "Crop Health",
    disease_risk: "Disease Risk",
    water_level: "Water Level",
    photo_view: "Photo View",
    fullscreen: "Full Screen",
    halfscreen: "Half Screen",
    locate_field: "Locate Field",
    spore_radius: "Spore Radius",
    pathology_dossier: "Plot Pathology Dossier",
    crop_variety: "Crop Variety",
    overall_health: "Overall Health",
    risk_zone: "Risk Zone",
    gps_coords: "GPS Coordinates",
    last_inspected: "Last Inspected",
    containment_protocol: "Containment Protocol",
    critical_blight: "Critical Blight",
    moderate_blight: "Moderate Blight",
    healthy_plots: "Healthy Plots",
    switch_language: "Select Language",
    powered_by_libre: "Powered by LibreTranslate",
  },
  hi: {
    nav_home: "होम",
    nav_scanner: "स्कैनर",
    nav_twin: "डिजिटल ट्विन",
    nav_radar: "रडार",
    nav_dosage: "दवा खुराक",
    nav_encyclopedia: "फसल ज्ञानकोश",
    nav_journal: "इतिहास",
    nav_scan_leaf: "पत्ती स्कैन करें",
    system_ready: "सिस्टम तैयार",
    api_offline: "ऑफ़लाइन",
    tagline: "पादप रोग पहचान प्रणाली",
    hero_title: "एआई सटीक कृषि और फसल रोग निदान प्रणाली",
    hero_subtitle: "त्वरित फसल रोग पहचान, मौसम पूर्वानुमान और स्वचालित ड्रोन छिड़काव सुरक्षा।",
    start_diagnosis: "जांच शुरू करें",
    explore_twin: "डिजिटल फार्म देखें",
    dosage_calc: "खुराक कैलकुलेटर",
    spore_radar: "रोग रडार",
    plant_encyclopedia: "ज्ञानकोश",
    scan_history: "स्कैन इतिहास",
    how_it_works: "यह कैसे काम करता है",
    select_field: "खेत चुनें",
    send_drone: "ड्रोन से छिड़काव करें",
    water_fields: "सिंचाई चालू करें",
    simulate_outbreak: "रोग प्रकोप सिमुलेशन",
    reset_farm: "फार्म रीसेट करें",
    crop_health: "फसल स्वास्थ्य",
    disease_risk: "रोग जोखिम",
    water_level: "जल स्तर",
    photo_view: "उपग्रह फोटो",
    fullscreen: "फुल स्क्रीन",
    halfscreen: "हाफ स्क्रीन",
    locate_field: "स्थान खोजें",
    spore_radius: "संक्रमण दायरा",
    pathology_dossier: "खेत रोग रिपोर्ट",
    crop_variety: "फसल किस्म",
    overall_health: "कुल स्वास्थ्य",
    risk_zone: "जोखिम क्षेत्र",
    gps_coords: "जीपीएस निर्देशांक",
    last_inspected: "अंतिम निरीक्षण",
    containment_protocol: "रोकथाम प्रोटोकॉल",
    critical_blight: "गंभीर रोग",
    moderate_blight: "मध्यम रोग",
    healthy_plots: "स्वस्थ खेत",
    switch_language: "भाषा चुनें",
    powered_by_libre: "LibreTranslate द्वारा अनुवादित",
  },
  es: {
    nav_home: "Inicio",
    nav_scanner: "Escáner",
    nav_twin: "Gemelo Digital",
    nav_radar: "Radar",
    nav_dosage: "Dosis",
    nav_encyclopedia: "Enciclopedia",
    nav_journal: "Historial",
    nav_scan_leaf: "Escanear Hoja",
    system_ready: "Sistema Listo",
    api_offline: "API Desconectada",
    tagline: "Sistema de Patología Vegetal",
    hero_title: "Agronomía de Precisión e Inteligencia de Cultivos con IA",
    hero_subtitle: "Diagnósticos instantáneos, pronósticos de esporas microclimáticas y defensa con drones autónomos.",
    start_diagnosis: "Iniciar Diagnóstico",
    explore_twin: "Explorar Gemelo Digital",
    dosage_calc: "Calculadora de Dosis",
    spore_radar: "Radar de Esporas",
    plant_encyclopedia: "Enciclopedia",
    scan_history: "Historial",
    how_it_works: "Cómo Funciona",
    select_field: "Seleccionar Parcela",
    send_drone: "Fumigar con Dron",
    water_fields: "Regar Parcelas",
    simulate_outbreak: "Simular Brote",
    reset_farm: "Restablecer Finca",
    crop_health: "Salud del Cultivo",
    disease_risk: "Riesgo de Enfermedad",
    water_level: "Nivel de Agua",
    photo_view: "Vista Satelital",
    fullscreen: "Pantalla Completa",
    halfscreen: "Media Pantalla",
    locate_field: "Ubicar Parcela",
    spore_radius: "Radio de Esporas",
    pathology_dossier: "Expediente de Patología",
    crop_variety: "Variedad de Cultivo",
    overall_health: "Salud General",
    risk_zone: "Zona de Riesgo",
    gps_coords: "Coordenadas GPS",
    last_inspected: "Última Inspección",
    containment_protocol: "Protocolo de Contención",
    critical_blight: "Tizón Crítico",
    moderate_blight: "Tizón Moderado",
    healthy_plots: "Parcelas Sanas",
    switch_language: "Seleccionar Idioma",
    powered_by_libre: "Traducido con LibreTranslate",
  },
  bn: {
    nav_home: "হোম",
    nav_scanner: "স্ক্যানার",
    nav_twin: "ডিজিটাল টুইন",
    nav_radar: "রাডার",
    nav_dosage: "ওষুধের মাত্রা",
    nav_encyclopedia: "বিশ্বকোষ",
    nav_journal: "ইতিহাস",
    nav_scan_leaf: "পাতা স্ক্যান করুন",
    system_ready: "সিস্টেম প্রস্তুত",
    api_offline: "অফলাইন",
    tagline: "উদ্ভিদ রোগ নির্ণয় পদ্ধতি",
    hero_title: "কৃষি নির্ভুলতা ও শস্য রোগ গোয়েন্দা ব্যবস্থা",
    hero_subtitle: "তাত্ক্ষণিক পাতার রোগ নির্ণয়, স্পোর পূর্বাভাস এবং স্বয়ংক্রিয় ড্রোন স্প্রে।",
    start_diagnosis: "পরীক্ষা শুরু করুন",
    explore_twin: "ডিজিটাল খামার দেখুন",
    dosage_calc: "ডোজ ক্যালকুলেটর",
    spore_radar: "স্পোর রাডার",
    plant_encyclopedia: "বিশ্বকোষ",
    scan_history: "স্ক্যান ইতিহাস",
    how_it_works: "এটি কীভাবে কাজ করে",
    select_field: "জমি নির্বাচন করুন",
    send_drone: "ড্রোন দিয়ে স্প্রে করুন",
    water_fields: "সেচ চালু করুন",
    simulate_outbreak: "রোগের প্রাদুর্ভাব অনুকরণ",
    reset_farm: "খামার পুনরায় সেট করুন",
    crop_health: "ফসলের স্বাস্থ্য",
    disease_risk: "রোগের ঝুঁকি",
    water_level: "পানির স্তর",
    photo_view: "স্যাটেলাইট ছবি",
    fullscreen: "পূর্ণ পর্দা",
    halfscreen: "অর্ধ পর্দা",
    locate_field: "অবস্থান সন্ধান করুন",
    spore_radius: "সংক্রমণের পরিসর",
    pathology_dossier: "জমির রোগ বিবরণী",
    crop_variety: "ফসলের জাত",
    overall_health: "সামগ্রিক স্বাস্থ্য",
    risk_zone: "ঝুঁকি অঞ্চল",
    gps_coords: "জিপিএস স্থানাঙ্ক",
    last_inspected: "শেষ পরিদর্শন",
    containment_protocol: "নিয়ন্ত্রণ প্রোটোকল",
    critical_blight: "মারাত্মক ব্লাইট",
    moderate_blight: "মাঝারি ব্লাইট",
    healthy_plots: "সুস্থ জমি",
    switch_language: "ভাষা নির্বাচন করুন",
    powered_by_libre: "LibreTranslate দ্বারা পরিচালিত",
  },
  pa: {
    nav_home: "ਘਰ",
    nav_scanner: "ਸਕੈਨਰ",
    nav_twin: "ਡਿਜੀਟਲ ਫਾਰਮ",
    nav_radar: "ਰਡਾਰ",
    nav_dosage: "ਦਵਾਈ ਦੀ ਖੁਰਾਕ",
    nav_encyclopedia: "ਜਾਣਕਾਰੀ ਕੋਸ਼",
    nav_journal: "ਇਤਿਹਾਸ",
    nav_scan_leaf: "ਪੱਤਾ ਸਕੈਨ ਕਰੋ",
    system_ready: "ਸਿਸਟਮ ਤਿਆਰ",
    api_offline: "ਆਫ਼ਲਾਈਨ",
    tagline: "ਪੌਦਿਆਂ ਦੀਆਂ ਬਿਮਾਰੀਆਂ ਦਾ ਪਤਾ ਲਗਾਉਣ ਵਾਲੀ ਪ੍ਰਣਾਲੀ",
    hero_title: "ਏਆਈ ਸ਼ੁੱਧ ਖੇਤੀਬਾੜੀ ਅਤੇ ਫਸਲ ਰੋਗ ਨਿਦਾਨ",
    hero_subtitle: "ਤੁਰੰਤ ਫਸਲ ਦੀ ਬਿਮਾਰੀ ਦੀ ਜਾਂਚ ਅਤੇ ਡਰੋਨ ਸਪਰੇਅ ਸੁਰੱਖਿਆ।",
    start_diagnosis: "ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ",
    explore_twin: "ਫਾਰਮ ਵੇਖੋ",
    dosage_calc: "ਖੁਰਾਕ ਕੈਲਕੁਲੇਟਰ",
    spore_radar: "ਰੋਗ ਰਡਾਰ",
    plant_encyclopedia: "ਜਾਣਕਾਰੀ ਕੋਸ਼",
    scan_history: "ਇਤਿਹਾਸ",
    how_it_works: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    select_field: "ਖੇਤ ਚੁਣੋ",
    send_drone: "ਡਰੋਨ ਨਾਲ ਸਪਰੇਅ ਕਰੋ",
    water_fields: "ਸਿੰਚਾਈ ਚਾਲੂ ਕਰੋ",
    simulate_outbreak: "ਬਿਮਾਰੀ ਦਾ ਪ੍ਰਕੋਪ ਟੈਸਟ",
    reset_farm: "ਫਾਰਮ ਰੀਸੈੱਟ ਕਰੋ",
    crop_health: "ਫਸਲ ਦੀ ਸਿਹਤ",
    disease_risk: "ਬਿਮਾਰੀ ਦਾ ਖਤਰਾ",
    water_level: "ਪਾਣੀ ਦਾ ਪੱਧਰ",
    photo_view: "ਸੈਟੇਲਾਈਟ ਫੋਟੋ",
    fullscreen: "ਪੂਰੀ ਸਕ੍ਰੀਨ",
    halfscreen: "ਅੱਧੀ ਸਕ੍ਰੀਨ",
    locate_field: "ਸਥਾਨ ਲੱਭੋ",
    spore_radius: "ਸੰਕਰਮਣ ਖੇਤਰ",
    pathology_dossier: "ਖੇਤ ਰਿਪੋਰਟ",
    crop_variety: "ਫਸਲ ਦੀ ਕਿਸਮ",
    overall_health: "ਕੁੱਲ ਸਿਹਤ",
    risk_zone: "ਖ਼ਤਰਾ ਖੇਤਰ",
    gps_coords: "ਜੀਪੀਐਸ ਨਿਰਦੇਸ਼ਾਂਕ",
    last_inspected: "ਆਖਰੀ ਨਿਰੀਖਣ",
    containment_protocol: "ਰੋਕਥਾਮ ਪ੍ਰੋਟੋਕੋਲ",
    critical_blight: "ਗੰਭੀਰ ਬਿਮਾਰੀ",
    moderate_blight: "ਦਰਮਿਆਨੀ ਬਿਮਾਰੀ",
    healthy_plots: "ਤੰਦਰੁਸਤ ਖੇਤ",
    switch_language: "ਭਾਸ਼ਾ ਚੁਣੋ",
    powered_by_libre: "LibreTranslate ਦੁਆਰਾ ਅਨੁਵਾਦਿਤ",
  },
  mr: {
    nav_home: "मुख्यपृष्ठ",
    nav_scanner: "स्कॅनर",
    nav_twin: "डिजिटल ट्विन",
    nav_radar: "रडार",
    nav_dosage: "मात्रा",
    nav_encyclopedia: "ज्ञानकोश",
    nav_journal: "इतिहास",
    nav_scan_leaf: "पान स्कॅन करा",
    system_ready: "प्रणाली सज्ज",
    api_offline: "ऑफलाइन",
    tagline: "वनस्पती रोग निदान प्रणाली",
    hero_title: "एआय अचूक शेती आणि पीक रोग निदान",
    hero_subtitle: "झटपट पीक रोग निदान, हवामान अंदाज आणि स्वयंचलित ड्रोन फवारणी.",
    start_diagnosis: "तपासणी सुरू करा",
    explore_twin: "डिजिटल शेत पहा",
    dosage_calc: "मात्रा गणक",
    spore_radar: "रोग रडार",
    plant_encyclopedia: "ज्ञानकोश",
    scan_history: "स्कॅन इतिहास",
    how_it_works: "हे कसे कार्य करते",
    select_field: "शेत निवडा",
    send_drone: "ड्रोनने फवारणी करा",
    water_fields: "सिंचन सुरू करा",
    simulate_outbreak: "रोग प्रादुर्भाव चाचणी",
    reset_farm: "शेत पूर्ववत करा",
    crop_health: "पीक आरोग्य",
    disease_risk: "रोग धोका",
    water_level: "पाणी पातळी",
    photo_view: "उपग्रह दृश्य",
    fullscreen: "पूर्ण स्क्रीन",
    halfscreen: "अर्धी स्क्रीन",
    locate_field: "स्थान शोधा",
    spore_radius: "संसर्ग त्रिज्या",
    pathology_dossier: "शेत रोग अहवाल",
    crop_variety: "पीक वाण",
    overall_health: "एकूण आरोग्य",
    risk_zone: "धोका क्षेत्र",
    gps_coords: "जीपीएस निर्देशांक",
    last_inspected: "शेवटची तपासणी",
    containment_protocol: "नियंत्रण नियम",
    critical_blight: "गंभीर करपा",
    moderate_blight: "मध्यम करपा",
    healthy_plots: "निरोगी शेत",
    switch_language: "भाषा निवडा",
    powered_by_libre: "LibreTranslate द्वारे समर्थित",
  },
  te: {
    nav_home: "హోమ్",
    nav_scanner: "స్కానర్",
    nav_twin: "డిజిటల్ ట్విన్",
    nav_radar: "రాడార్",
    nav_dosage: "మోతాదు",
    nav_encyclopedia: "విజ్ఞాన సర్వస్వం",
    nav_journal: "చరిత్ర",
    nav_scan_leaf: "ఆకును స్కాన్ చేయండి",
    system_ready: "వ్యవస్థ సిద్ధంగా ఉంది",
    api_offline: "ఆఫ్‌లైన్",
    tagline: "మొక్కల వ్యాధి నిర్ధారణ వ్యవస్థ",
    hero_title: "ఏఐ ఖచ్చితమైన వ్యవసాయం మరియు పంట వ్యాధి నిర్ధారణ",
    hero_subtitle: "తక్షణ పంట వ్యాధి నిర్ధారణ, వాతావరణ అంచనాలు మరియు డ్రోన్ రక్షణ.",
    start_diagnosis: "తనిఖీ ప్రారంభించండి",
    explore_twin: "డిజిటల్ ఫారమ్ చూడండి",
    dosage_calc: "మోతాదు కాలిక్యులేటర్",
    spore_radar: "వ్యాధి రాడార్",
    plant_encyclopedia: "విజ్ఞాన సర్వస్వం",
    scan_history: "స్కాన్ చరిత్ర",
    how_it_works: "ఇది ఎలా పనిచేస్తుంది",
    select_field: "పొలం ఎంచుకోండి",
    send_drone: "డ్రోన్ తో స్ప్రే చేయండి",
    water_fields: "నీటిపారుదల ప్రారంభించండి",
    simulate_outbreak: "వ్యాధి వ్యాప్తి అనుకరణ",
    reset_farm: "ఫారం రీసెట్ చేయండి",
    crop_health: "పంట ఆరోగ్యం",
    disease_risk: "వ్యాధి ప్రమాదం",
    water_level: "నీటి స్థాయి",
    photo_view: "శాటిలైట్ ఫోటో",
    fullscreen: "పూర్తి స్క్రీన్",
    halfscreen: "సగం స్క్రీన్",
    locate_field: "లొకేషన్ కనుగొనండి",
    spore_radius: "వ్యాప్తి వ్యాసార్థం",
    pathology_dossier: "పొలం నివేదిక",
    crop_variety: "పంట రకం",
    overall_health: "మొత్తం ఆరోగ్యం",
    risk_zone: "ప్రమాద ప్రాంతం",
    gps_coords: "జీపీఎస్ కోఆర్డినేట్స్",
    last_inspected: "చివరి తనిఖీ",
    containment_protocol: "నియంత్రణ ప్రోటోకాల్",
    critical_blight: "తీవ్రమైన తెగులు",
    moderate_blight: "మధ్యస్థ తెగులు",
    healthy_plots: "ఆరోగ్యకరమైన పొలాలు",
    switch_language: "భాషను ఎంచుకోండి",
    powered_by_libre: "LibreTranslate ద్వారా అనువదించబడింది",
  },
  ta: {
    nav_home: "முகப்பு",
    nav_scanner: "ஸ்கேனர்",
    nav_twin: "டிஜிட்டல் பண்ணை",
    nav_radar: "ரேடார்",
    nav_dosage: "மருந்து அளவு",
    nav_encyclopedia: "களஞ்சியம்",
    nav_journal: "வரலாறு",
    nav_scan_leaf: "இலையை ஸ்கேன் செய்",
    system_ready: "அமைப்பு தயார்",
    api_offline: "ஆஃப்லைன்",
    tagline: "தாவர நோய் கண்டறிதல் அமைப்பு",
    hero_title: "AI துல்லிய வேளாண்மை மற்றும் பயிர் நோய் நுண்ணறிவு",
    hero_subtitle: "உடனடி தாவர நோய் கண்டறிதல், வானிலை எச்சரிக்கை மற்றும் ட்ரோன் தெளிப்பு பாதுகாப்பு.",
    start_diagnosis: "ஆரம்பிக்கவும்",
    explore_twin: "பண்ணையை பார்க்கவும்",
    dosage_calc: "மருந்து கால்குலேட்டர்",
    spore_radar: "நோய் ரேடார்",
    plant_encyclopedia: "களஞ்சியம்",
    scan_history: "ஸ்கேன் வரலாறு",
    how_it_works: "எவ்வாறு செயல்படுகிறது",
    select_field: "நிலத்தை தேர்வு செய்க",
    send_drone: "ட்ரோன் மூலம் தெளிக்கவும்",
    water_fields: "பாசனம் செய்க",
    simulate_outbreak: "நோய் பரவல் சோதனை",
    reset_farm: "பண்ணையை மீட்டமைக்கவும்",
    crop_health: "பயிர் நலம்",
    disease_risk: "நோய் அபாயம்",
    water_level: "நீர் அளவு",
    photo_view: "செயற்கைக்கோள் காட்சி",
    fullscreen: "முழுத்திரை",
    halfscreen: "அரைத்திரை",
    locate_field: "இருப்பிடத்தைக் காண்க",
    spore_radius: "பரவல் ஆரம்",
    pathology_dossier: "நோய் அறிக்கை",
    crop_variety: "பயிர் ரகம்",
    overall_health: "ஒட்டுமொத்த நலம்",
    risk_zone: "அபாய மண்டலம்",
    gps_coords: "ஜிபிஎஸ் ஒருங்கிணைப்புகள்",
    last_inspected: "கடைசி ஆய்வு",
    containment_protocol: "கட்டுப்பாட்டு விதிமுறைகள்",
    critical_blight: "தீவிர நோய்",
    moderate_blight: "மிதமான நோய்",
    healthy_plots: "ஆரோக்கியமான நிலங்கள்",
    switch_language: "மொழியைத் தேர்வுசெய்",
    powered_by_libre: "LibreTranslate மூலம் இயக்கப்படுகிறது",
  },
  fr: {
    nav_home: "Accueil",
    nav_scanner: "Scanner",
    nav_twin: "Jumeau Numérique",
    nav_radar: "Radar",
    nav_dosage: "Dosage",
    nav_encyclopedia: "Encyclopédie",
    nav_journal: "Journal",
    nav_scan_leaf: "Scanner Feuille",
    system_ready: "Système Prêt",
    api_offline: "API Hors Ligne",
    tagline: "Système de Pathologie Végétale",
    hero_title: "Agronomie de Précision et Intelligence Phytopathologique IA",
    hero_subtitle: "Diagnostics instantanés, prévision des spores microclimatiques et défense par drones autonomes.",
    start_diagnosis: "Démarrer Diagnostic",
    explore_twin: "Explorer la Ferme",
    dosage_calc: "Calculateur de Dosage",
    spore_radar: "Radar de Spores",
    plant_encyclopedia: "Encyclopédie",
    scan_history: "Historique",
    how_it_works: "Comment ça marche",
    select_field: "Sélectionner Parcelle",
    send_drone: "Pulvériser par Drone",
    water_fields: "Arroser les Champs",
    simulate_outbreak: "Simuler Épidémie",
    reset_farm: "Réinitialiser Ferme",
    crop_health: "Santé des Cultures",
    disease_risk: "Risque de Maladie",
    water_level: "Niveau d'Eau",
    photo_view: "Vue Satellite",
    fullscreen: "Plein Écran",
    halfscreen: "Demi-Écran",
    locate_field: "Localiser Parcelle",
    spore_radius: "Rayon de Spores",
    pathology_dossier: "Dossier Pathologique",
    crop_variety: "Variété de Culture",
    overall_health: "Santé Globale",
    risk_zone: "Zone de Risque",
    gps_coords: "Coordonnées GPS",
    last_inspected: "Dernière Inspection",
    containment_protocol: "Protocole de Confinement",
    critical_blight: "Mildiou Critique",
    moderate_blight: "Mildiou Modéré",
    healthy_plots: "Parcelles Saines",
    switch_language: "Changer de Langue",
    powered_by_libre: "Traduit par LibreTranslate",
  },
  de: {
    nav_home: "Startseite",
    nav_scanner: "Scanner",
    nav_twin: "Digitaler Zwilling",
    nav_radar: "Radar",
    nav_dosage: "Dosierung",
    nav_encyclopedia: "Enzyklopädie",
    nav_journal: "Journal",
    nav_scan_leaf: "Blatt Scannen",
    system_ready: "System Bereit",
    api_offline: "API Offline",
    tagline: "Pflanzenpathologie-System",
    hero_title: "KI-Präzisionsagronomie & Pflanzenschutz-Intelligenz",
    hero_subtitle: "Sofortige neuronale Diagnostik, Sporen-Mikroklima-Vorhersage und autonome Drohnenabwehr.",
    start_diagnosis: "Diagnose Starten",
    explore_twin: "Farm-Zwilling Erkunden",
    dosage_calc: "Dosierungsrechner",
    spore_radar: "Sporenradar",
    plant_encyclopedia: "Enzyklopädie",
    scan_history: "Verlauf",
    how_it_works: "So Funktioniert Es",
    select_field: "Feld Auswählen",
    send_drone: "Mit Drohne Besprühen",
    water_fields: "Felder Bewässern",
    simulate_outbreak: "Ausbruch Simulieren",
    reset_farm: "Farm Zurücksetzen",
    crop_health: "Pflanzengesundheit",
    disease_risk: "Krankheitsrisiko",
    water_level: "Wasserstand",
    photo_view: "Satellitenfoto",
    fullscreen: "Vollbild",
    halfscreen: "Halbbild",
    locate_field: "Feld Lokalisieren",
    spore_radius: "Sporenradius",
    pathology_dossier: "Pathologie-Dossier",
    crop_variety: "Pflanzenart",
    overall_health: "Gesamtzustand",
    risk_zone: "Risikozone",
    gps_coords: "GPS-Koordinaten",
    last_inspected: "Zuletzt Geprüft",
    containment_protocol: "Eindämmungsprotokoll",
    critical_blight: "Kritischer Befall",
    moderate_blight: "Mäßiger Befall",
    healthy_plots: "Gesunde Felder",
    switch_language: "Sprache Wählen",
    powered_by_libre: "Übersetzt mit LibreTranslate",
  },
  zh: {
    nav_home: "首页",
    nav_scanner: "病害扫描",
    nav_twin: "数字孪生农场",
    nav_radar: "气象雷达",
    nav_dosage: "用药剂量",
    nav_encyclopedia: "病害百科",
    nav_journal: "诊断记录",
    nav_scan_leaf: "扫描叶片",
    system_ready: "系统就绪",
    api_offline: "接口离线",
    tagline: "植物病理智能分析系统",
    hero_title: "AI精准农业与作物病害智能诊断",
    hero_subtitle: "实时神经病害诊断、微气候孢子扩散预警和自主无人机精准植保。",
    start_diagnosis: "开始诊断",
    explore_twin: "探索数字农场",
    dosage_calc: "用药计算器",
    spore_radar: "病菌雷达",
    plant_encyclopedia: "作物百科",
    scan_history: "扫描历史",
    how_it_works: "使用指南",
    select_field: "选择地块",
    send_drone: "无人机喷药",
    water_fields: "开启灌溉",
    simulate_outbreak: "模拟病害爆发",
    reset_farm: "重置农场",
    crop_health: "作物长势",
    disease_risk: "病害风险",
    water_level: "土壤水分",
    photo_view: "卫星影像",
    fullscreen: "全屏模式",
    halfscreen: "半屏模式",
    locate_field: "定位地块",
    spore_radius: "孢子扩散半径",
    pathology_dossier: "地块病理档案",
    crop_variety: "作物品种",
    overall_health: "综合健康度",
    risk_zone: "风险等级",
    gps_coords: "经纬度坐标",
    last_inspected: "最新巡检",
    containment_protocol: "防控方案",
    critical_blight: "严重晚疫病",
    moderate_blight: "中度早疫病",
    healthy_plots: "健康地块",
    switch_language: "选择语言",
    powered_by_libre: "由 LibreTranslate 强力驱动",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_scanner: "الماسح الضوئي",
    nav_twin: "المزرعة الرقمية",
    nav_radar: "الرادار",
    nav_dosage: "الجرعات",
    nav_encyclopedia: "الموسوعة",
    nav_journal: "السجل",
    nav_scan_leaf: "مسح الورقة",
    system_ready: "النظام جاهز",
    api_offline: "غير متصل",
    tagline: "نظام تشخيص أمراض النبات",
    hero_title: "الزراعة الدقيقة بالذكاء الاصطناعي وكشف أمراض المحاصيل",
    hero_subtitle: "تشخيص فوري للأمراض وتنبؤ بالجراثيم ودفاع آلي بالطائرات بدون طيار.",
    start_diagnosis: "بدء الفحص",
    explore_twin: "استكشاف المزرعة",
    dosage_calc: "حاسبة الجرعات",
    spore_radar: "رادار الجراثيم",
    plant_encyclopedia: "الموسوعة",
    scan_history: "السجل",
    how_it_works: "كيف يعمل",
    select_field: "حدد الحقل",
    send_drone: "رش بالطائرة المسيرة",
    water_fields: "تشغيل الري",
    simulate_outbreak: "محاكاة انتشار المرض",
    reset_farm: "إعادة ضبط المزرعة",
    crop_health: "صحة المحصول",
    disease_risk: "مخاطر المرض",
    water_level: "مستوى المياه",
    photo_view: "صورة القمر الصناعي",
    fullscreen: "ملء الشاشة",
    halfscreen: "نصف شاشة",
    locate_field: "تحديد الموقع",
    spore_radius: "نطاق العدوى",
    pathology_dossier: "تقرير أمراض الحقل",
    crop_variety: "نوع المحصول",
    overall_health: "الصحة العامة",
    risk_zone: "منطقة الخطر",
    gps_coords: "إحداثيات GPS",
    last_inspected: "آخر فحص",
    containment_protocol: "بروتوكول الاحتواء",
    critical_blight: "لفحة شديدة",
    moderate_blight: "لفحة متوسطة",
    healthy_plots: "حقول سليمة",
    switch_language: "اختر اللغة",
    powered_by_libre: "مترجم بواسطة LibreTranslate",
  },
  pt: {
    nav_home: "Início",
    nav_scanner: "Scanner",
    nav_twin: "Gêmeo Digital",
    nav_radar: "Radar",
    nav_dosage: "Dosagem",
    nav_encyclopedia: "Enciclopédia",
    nav_journal: "Histórico",
    nav_scan_leaf: "Escanear Folha",
    system_ready: "Sistema Pronto",
    api_offline: "API Offline",
    tagline: "Sistema de Fitopatologia",
    hero_title: "Agronomia de Precisão e Diagnóstico de Doenças com IA",
    hero_subtitle: "Diagnósticos neurais instantâneos, previsão de esporos e defesa autônoma com drones.",
    start_diagnosis: "Iniciar Diagnóstico",
    explore_twin: "Explorar Fazenda",
    dosage_calc: "Calculadora de Dosagem",
    spore_radar: "Radar de Esporos",
    plant_encyclopedia: "Enciclopédia",
    scan_history: "Histórico",
    how_it_works: "Como Funciona",
    select_field: "Selecionar Campo",
    send_drone: "Pulverizar com Drone",
    water_fields: "Irrigar Campos",
    simulate_outbreak: "Simular Surto",
    reset_farm: "Redefinir Fazenda",
    crop_health: "Saúde da Cultura",
    disease_risk: "Risco de Doença",
    water_level: "Nível de Água",
    photo_view: "Visualização Satélite",
    fullscreen: "Tela Cheia",
    halfscreen: "Meia Tela",
    locate_field: "Localizar Campo",
    spore_radius: "Raio de Esporos",
    pathology_dossier: "Dossiê Fitopatológico",
    crop_variety: "Variedade da Cultura",
    overall_health: "Saúde Geral",
    risk_zone: "Zona de Risco",
    gps_coords: "Coordenadas GPS",
    last_inspected: "Última Inspeção",
    containment_protocol: "Protocolo de Contenção",
    critical_blight: "Requeima Crítica",
    moderate_blight: "Pinta Preta Moderada",
    healthy_plots: "Campos Saudáveis",
    switch_language: "Selecionar Idioma",
    powered_by_libre: "Traduzido com LibreTranslate",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem("agropath_language") || "en";
  });
  const [isTranslating, setIsTranslating] = useState(false);
  const [dynamicCache, setDynamicCache] = useState({});

  // Sync HTML lang and dir attributes
  useEffect(() => {
    document.documentElement.lang = currentLang;
    document.documentElement.dir = currentLang === "ar" ? "rtl" : "ltr";
    localStorage.setItem("agropath_language", currentLang);
  }, [currentLang]);

  // Synchronous Instant Key Translation (Fallback to English if key missing)
  const t = useCallback(
    (key, fallback = "") => {
      const langDict = UI_DICTIONARY[currentLang];
      if (langDict && langDict[key]) {
        return langDict[key];
      }
      const enDict = UI_DICTIONARY.en;
      if (enDict && enDict[key]) {
        return enDict[key];
      }
      return fallback || key;
    },
    [currentLang]
  );

  // Dynamic Asynchronous Translation via LibreTranslate API
  const translateWithLibre = useCallback(
    async (text, targetLanguage = currentLang) => {
      if (!text || typeof text !== "string" || !text.trim()) return text;
      if (targetLanguage === "en") return text;

      const cacheKey = `${targetLanguage}_${text.trim()}`;
      if (dynamicCache[cacheKey]) {
        return dynamicCache[cacheKey];
      }

      try {
        setIsTranslating(true);
        const res = await fetch(`${API_BASE_URL}/api/translate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            q: text,
            source: "en",
            target: targetLanguage,
            format: "text",
          }),
        });

        if (res.ok) {
          const data = await res.json();
          const translated = data.translatedText || text;
          setDynamicCache((prev) => ({ ...prev, [cacheKey]: translated }));
          return translated;
        }
      } catch (err) {
        console.warn("LibreTranslate API warning:", err);
      } finally {
        setIsTranslating(false);
      }

      return text;
    },
    [currentLang, dynamicCache]
  );

  const changeLanguage = (langCode) => {
    const found = SUPPORTED_LANGUAGES.find((l) => l.code === langCode);
    if (found) {
      setCurrentLang(langCode);
    }
  };

  const activeLanguageObj =
    SUPPORTED_LANGUAGES.find((l) => l.code === currentLang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        activeLanguageObj,
        languages: SUPPORTED_LANGUAGES,
        changeLanguage,
        t,
        translateWithLibre,
        isTranslating,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
};
